// // <copyright file="SettingsData.cs" company="PublicDomain.is">
// //     CC0 1.0 Universal (CC0 1.0) - Public Domain Dedication
// //     https://creativecommons.org/publicdomain/zero/1.0/legalcode
// // </copyright>
// // <auto-generated />

namespace PublicDomain
{
    // Directives
    using System.Collections.Generic;
    using System.Drawing;

    /// <summary>
    /// Urlister settings.
    /// </summary>
    public class SettingsData
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="T:PublicDomain.SettingsData"/> class.
        /// </summary>
        public SettingsData()
        {
            // Parameterless constructor
        }

        /// <summary>
        /// Gets or sets the directory.
        /// </summary>
        /// <value>The directory.</value>
        public string Directory { get; set; } = string.Empty;

        /// <summary>
        /// Gets or sets the location.
        /// </summary>
        /// <value>The location.</value>
        public Point Location { get; set; } = new Point(0, 0);

        /// <summary>
        /// Gets or sets the size.
        /// </summary>
        /// <value>The size.</value>
        public Size Size { get; set; } = new Size(0, 0);

        /// <summary>
        /// Gets or sets the vertical split.
        /// </summary>
        /// <value>The vertical split.</value>
        public int VerticalSplit { get; set; } = 0;

        /// <summary>
        /// Gets or sets the horizontal split.
        /// </summary>
        /// <value>The horizontal split.</value>
        public int HorizontalSplit { get; set; } = 0;
    }
}